CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(16) NOT NULL,
    password VARCHAR(128) NOT NULL,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE
);