CREATE TABLE IF NOT EXISTS payment (
    id SERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES store(id) ON DELETE CASCADE,
    deal_id BIGINT NOT NULL REFERENCES deal(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES user_(id) ON DELETE CASCADE,
    sender_id BIGINT DEFAULT NULL REFERENCES contact(id) ON DELETE CASCADE,
    receiver_id BIGINT DEFAULT NULL REFERENCES contact(id) ON DELETE CASCADE,
    
    amount DECIMAL(10, 2) NOT NULL CHECK (amount > 0),
    type VARCHAR(16) NOT NULL,
    method VARCHAR(16) NOT NULL,
    category VARCHAR(16) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
